# Basic Config ---

# Project information
site_name: ASGI WebDAV Server Documentation
site_url: https://rexzhang.github.io/asgi-webdav/

# Repository
repo_name: rexzhang/asgi-webdav
repo_url: https://rexzhang.github.io/asgi-webdav

# Additional configuration ---
extra:
  alternate:
    - name: English
      link: ./
      lang: en
    - name: 中文
      link: ./zh/
      lang: zh

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rexzhang/asgi-webdav
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/ray1ex/asgi-webdav

# Theme ---
theme:
  name: materialx
  font: false

  features:
    - content.action.edit
    - content.action.view
    - content.action.agents
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.footnote.tooltips
    - content.tooltips

    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    # - navigation.expand
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.footer

    - search.highlight
    - search.share
    - search.suggest

    - toc.follow
    # - toc.integrate

  topbar_style: primary
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - stylesheets/extra.css

# Plugins & Hooks ---
plugins:
  # Built-in plugin
  # https://jaywhj.github.io/mkdocs-materialx/plugins/index.html#built-in-plugins
  - search
  - document-dates:
      position: top
      type: date
      exclude:
        - temp.md
        - blog/*

  # https://lukasgeiter.github.io/mkdocs-awesome-nav/
  - awesome-nav

  # https://github.com/ultrabug/mkdocs-static-i18n
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            Home: 首页
            Get Started: 开始
            Guidebook: 指南
            Reference: 参考
            Trouble Shooting: 问题处理

# Extensions ---
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      toc_depth: 4
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
    # smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      # linenums: true
      # linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path:
        - docs
        - .
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      relaxed_headers: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # - material.extensions.code_download
