nav:
  - Home:
      # 项目相关
      - index.md
      - compatibility.md
      - changelog.md
      - contributing.md
      - acknowledgements.md
  - Get Started:
      # setup
      - setup/quick-start-in-docker.md
      - setup/install.md
      - setup/config.md
  - Guidebook:
      # 具体到某一个功能的使用说明
      - Guides: guide
      - How To: howto
  - Reference:
      # 详细的参考文档
      - Common: reference/common
      - Provider: reference/provider
  - Trouble Shooting:
      - known-issues.md
      - trouble-shooting.md
