name: Release docs to GitHub Pages

# https://github.com/jaywhj/mkdocs-materialx/blob/main/.github/workflows/documentation.yml

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.x

permissions:
  contents: write

jobs:
  documentation:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
            includes
            material
            src/templates/partials/languages
            mkdocs.yml

      - name: Set up Python runtime
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: sudo apt-get install pngquant

      - name: Install Python dependencies
        run: |
          pip install -U -r requirements.d/mkdocs.txt

      - name: Deploy to gh-pages
        run: mkdocs gh-deploy --force
